### ISSUE TITLE
Remove ART from Value section

### ISSUE THREAD

**Issue by dcory** [tableau/tableau-log-viewer#105]
Can we remove the ART data from the Value section? It's so much harder to read the logs with that extra material in the way.

**Comment by alv53** [comment]
Alternatively we could have TLV parse the ART data and show it in a more human readable way.

**Comment by dcory** [comment]
Showing it only when I hover over the ART bullet would be great.

**Comment by terencesoh** [comment]
We currently do show the ART data when hovering over the ART bullet. Perhaps we could add a check box option to hide the ART and error code data in value dialog.

**Comment by dcory** [comment]
It would be useful to hide it from the Value dialog, but I really want to hide it in the Value column in the main view.

**Comment by luiseeo** [comment]
This has been a recurring complain ("ART data is cool... but I don't need to see it all the time and it makes the rest of the logs more difficult to read")

**Comment by luiseeo** [comment]
Issue was fixed
