### ISSUE TITLE
is there a max tree size that the viewer will visualize?

### ISSUE THREAD

**Issue by korompaiistvan** [tableau/tableau-log-viewer#114]
I have large query trees that I'd like to optimize. (in some cases exceeding 500k nodes, as known from the relevant error message)
when trying to visualise these, I click the button and nothing happens (i suppose due to the excessive size). 
Is this expected?

**Comment by luiseeo** [comment]
Loading the visualization gets more slow the more nodes it needs to display. But I'm not sure if you are hitting a very slow load or a bug. Can you please attach the document you are trying to visualize?

**Comment by korompaiistvan** [comment]
I'm working on anonymizing the log entry. what's the best format for me to share just the one line?

**Comment by korompaiistvan** [comment]
couldn't provide the log entry filed, closing the issue
