### ISSUE TITLE
Weird behavior of find window

### ISSUE THREAD

**Issue by Bk8** [tableau/tableau-log-viewer#119]
The find window should not close because multiple instances of a string could exist and this finds just the first ocurrence. It should work similarly to the Microsoft Word search window.

**Comment by luiseeo** [comment]
Hi, thanks for your feedback.
Is it possible to find all occurrences of a search. Although the find window closes after finding the first occurrence, you can continue finding the rest of the occurrences by using the find menu:
![image](https://user-images.githubusercontent.com/1087437/71530661-b9c79f80-289f-11ea-82aa-92d921486d4f.png)
Or, as the menu suggests, by using the keyboard shortcuts (`F3` and `Shift+F3` in Windows)

You bring to out attention that the User Experience for finding out this functionality is not intuitive. Would adding a `Next` button in the find dialog and not closing the dialog after the first search help?

**Comment by Bk8** [comment]
Yes thats a lot better. Thanks! Hope you implement this! Sorry for the late reply

**Comment by luiseeo** [comment]
Issue addressed with change d920d18
