### ISSUE TITLE
TLV Project file contains back slashes

### ISSUE THREAD

**Issue by russch** [tableau/tableau-log-viewer#13]
Which might scare people when qmake throws warnings:

```
qmake -spec macx-clang CONFIG+=x86_64 -Wall ~/Development/tableau-log-viewer/src/tableau-log-viewer.pro
WARNING: /Users/russch/Qt/5.7/clang_64/mkspecs/features/resources.prf:22: Unescaped backslashes are deprecated
```

**Comment by whenamanlies** [comment]
I'm not sure where this is coming from as only backslashes we have are here:
`DEFINES += APP_VERSION=\\\"$$VERSION\\\"`

**Comment by whenamanlies** [comment]
@russch , warning comes from resources.prf which is a clang's file and come with Qt. It has following line:
`contains(resource, ".*\.qrc$"): \`

We can't change that file and I don't want to put arbitrary pragma or flag to ignore this error for the project.

Closing.
