### ISSUE TITLE
Could not find mkspecs for your QMAKESPEC(macx-clang-32)

### ISSUE THREAD

**Issue by hasStephen** [tableau/tableau-log-viewer#31]
Throws this error
`Could not find mkspecs for your QMAKESPEC(macx-clang-32) after trying:
	/anaconda/mkspecs
Error processing project file: src/tableau-log-viewer.pro`

when I try to run `qmake -spec macx-clang CONFIG+=x86_64 -Wall /src/tableau-log-viewer.pro`

I'm currently running osx 10.11.6 and anaconda 3.19.0

Is anyone else seeing something like this?

**Comment by luiseeo** [comment]
Have you tried using a non-anaconda Qt (like the one from http://qt.io)? You might need to add the Qt bin folder to the path before running qmake

```bash
# Find out where the Qt libraries are stored in your disk drive, and add the directory to the PATH.
# It should look something like this
export PATH="~/Qt/5.7/clang_64/bin":$PATH
```

**Comment by whenamanlies** [comment]
Also, we have packaged binaries under master release in case you just want to use it.

**Comment by vogelsgesang** [comment]
should we close this issue?
Or are we still planning to do anything related to this issue?
