### ISSUE TITLE
Could not build on Windows

### ISSUE THREAD

**Issue by scrocker** [tableau/tableau-log-viewer#32]
Can't build on Windows 10.  I've tried all methods.  nothing works just get errors
![capture](https://cloud.githubusercontent.com/assets/9084274/20279999/618237e6-aa70-11e6-99b2-48a0c22b63c4.JPG)

**Comment by whenamanlies** [comment]
We have packaged binaries under master's Release in case you just want to use it. 
I wonder what sort of dependency is missing in your case...

**Comment by terencesoh** [comment]
@scrocker Could you provide info on what compiler are you using? I have been able to build it on Windows 10 with Qt Creator 5.7 and Visual Studio 2015.

**Comment by scrocker** [comment]
I have Windows 10 with Qt 5.6.3x86-msvc2013_64   Visual studio 2013.  And GitBash installed

 

I’m new to this but followed the instructions to the letter. (I think)

**Comment by scrocker** [comment]
Dmitry I don’t see any binaries under master. Just the

**Comment by terencesoh** [comment]
The binaries can be found as ZIP files at: https://github.com/tableau/tableau-log-viewer/releases

**Comment by scrocker** [comment]
Thank you Terence, I wasn’t seeing that where I was going.  Much Appreciated

**Comment by terencesoh** [comment]
Glad to be of help.  The GitHub page is not easy to navigate from that POV, as the release links are not on the top level tabs. We will be updating the main release note with proper links to minimize the confusions.

If you still want to resolve the build errors, it would be helpful to attach the log from the "Compile Output", so we can examine the actual tools and errors.  I would also check the Kits setup - click the Projects on left side bar, then "Manage Kits..." button, and check the "Kit" used is using Visual C++ compiler and corresponding version of Qt.

**Comment by rgsmca** [comment]
I tried to setup this utility on window server 2008. Not working. it showed an error "missing msvcp120.dll" file while launching this application. it is not working even I placed this DLL ( tried both 32, 64 bit )

**Comment by luiseeo** [comment]
Hi. Unfortunately we haven't tried running Tableau Log Viewer on a Windows Server system.

According to this [post](https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/missing-msvcp120dll-file/f0a14d55-73f0-4a21-879e-1cbacf05e906?auth=1), you might need to re-install the Visual C++ Redistributable Package (BOTH x86 and x64), which you can get from here:
http://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by terencesoh** [comment]
Checked that building on Windows 10 and running on Windows Server 2008 are OK.
