### ISSUE TITLE
Wrap text option is not persisted

### ISSUE THREAD

**Issue by alv53** [tableau/tableau-log-viewer#57]
Happening in the latest TLV (from Luis's click once installer).

Steps to repro:
1. Open a log entry. Notice that wrap text is checked by default
2. Uncheck the wrap text option
3. Close the log entry
4. Open the same or another log entry

Expected: Wrap text is disabled
Actual: Wrap text is enabled again (by default)

**Comment by luiseeo** [comment]
Issue is fixed
