### ISSUE TITLE
Relax restrictions on filter names (i.e. allow "end-query")

### ISSUE THREAD

**Issue by whenamanlies** [tableau/tableau-log-viewer#6]
If I attempt to name highlight filter something like "end-query" then I get following error:
    _Only alphanumeric characters and underscores are allowed._

![image](https://cloud.githubusercontent.com/assets/9501144/19399293/af7a19ce-9205-11e6-8ea7-5970a00cfa78.png)

That name is used as a file name so let's allow everything that file system can handle.

**Comment by alv53** [comment]
Based on
http://superuser.com/questions/358855/what-characters-are-safe-in-cross-platform-file-names-for-linux-windows-and-os
It seems like we can safely added dashes and spaces, so I will do that. Are there any other characters that come to mind that we explicitly want to allow?

**Comment by whenamanlies** [comment]
Dot is the only character that comes to mind.

**Comment by whenamanlies** [comment]
Resolved by #16
