### ISSUE TITLE
Feature request add support for the "a" key recently added in the logs

### ISSUE THREAD

**Issue by luiseeo** [tableau/tableau-log-viewer#76]
There a new top level key in Tableau logs, which is "a", I think it stands for "activity".  TLV is currently unable to display this information. This would probably be a new column (just like "Time" and "Value" are now).

Example of event:
`{"ts":"2017-11-15T17:05:09.898","pid":50992,"tid":"bf10","sev":"info","req":"-","sess":"-","site":"{5843357A-1609-4CB9-BBF1-C4307BBCC217}","user":"-","k":"end-ds-connect-data-connection","a":{"depth":3,"elapsed":0.064,"end":"2017-11-16T01:05:09.842Z","id":"P/////U30nQP/////30IOX","name":"ds-connect-data-connection","res":{"alloc":{"e":"4.42e+03","i":"4.67e+06","ne":50,"ni":54037},"free":{"e":"3.11e+03","i":"1.58e+06","ne":33,"ni":9296}},"rk":"success","rv":"","sponsor":"J+JTXBxiUHGP////+0fkqw","type":"end","view":"","workbook":""},"v":{"caption":"Airport","elapsed":0.064,"name":"Airport"}}`

One tricky thing is that "a" has nested objects and the the collapsing/expanding might conflict with Value (how to display both?)

**Comment by whenamanlies** [comment]
I haven't read enough about this yet to evaluate.

**Comment by vogelsgesang** [comment]
We decided to postpone this feature until the `a` usage is more widespread or until we get more requests to add support for it
