### ISSUE TITLE
The content is not splitted accordingly in to columns 

### ISSUE THREAD

**Issue by bamarghioali** [tableau/tableau-log-viewer#90]
Hello,

I'm investigating TLV as a possible solution to quickly parse Tableau Server Logs.

It's seems very useful with handy options existing out-of-the-box.

I've noticed that the column "value" also contains the time info; if I also put the check to display the time column the rows for the column are empty so the data is not splitted accordingly (please see the attached image).
<img width="964" alt="capture" src="https://user-images.githubusercontent.com/32478379/38559554-0118b9d4-3cdc-11e8-9cfd-9fddd888dd36.PNG">

How can I solve this?

Thanks,
Bogdan

**Comment by vogelsgesang** [comment]
Hi Bodgan,

I am glad to hear that you like our little tool

The Tableau Log Viewer is primarily built to view Tableau's custom log format. It is written for example by Tableau Desktop, Hyper and a few other parts of the Tableau stack.

The log file you are opening looks to me like a log file written by Apache or some similar webserver. Unfortunately, we don't fully support loading this file format yet.

Personally, I hope we will add support for other file formats, such as Apache logs. Right now, we are currently not actively working on it. But pull requests are always welcome, of course :)

Cheers,
Adrian

**Comment by bamarghioali** [comment]
Hi Adrian,

Thank you for your answer, you're right the log file is for httpd.

I will use TLV like so; if this kind of file will be supported in the future it will be appreciated.

Thanks,
Bogdan
