### ISSUE TITLE
Windows git bash "WARNING: H:/Qt/5.6/msvc2013_64/mkspecs/features/resources.prf:22: Unescaped backslashes are deprecated"

### ISSUE THREAD

**Issue by linux2014linux** [tableau/tableau-log-viewer#92]
$ qmake -spec win32-msvc2013 CONFIG+=x86_64 -Wall ../src/tableau-log-viewer.pro
WARNING: H:/Qt/5.6/msvc2013_64/mkspecs/features/resources.prf:22: Unescaped backslashes are deprecated

**Comment by vogelsgesang** [comment]
As far as I understand, this is an warning message triggered by a script shipped with Qt.
I don't think we can do anything about it, can we?

**Comment by terencesoh** [comment]
Yes, this is a Qt issue. It's fixed in 5.8+. https://codereview.qt-project.org/#/c/183056/
Since I've moved the appveyor config to use 5.11.0, we can close this now.
